---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
date: "2024-10-21"
---
```{r}
library(sf)
library(here)
World <- st_read(here("World_Countries_(Generalized)_9029012925078512962.geojson"))
print(World)
```
ˆ
```{r}
CompData<-read.csv("HDR23-24_Composite_indices_complete_time_series.csv",
                   header = TRUE,
                   sep = ",",
                   encoding = "latin1")
cd_col <- colnames(CompData)
print(cd_col)
```
```{r}
library(dplyr)
gii_world <- CompData %>%
  select(iso3,
         country,
         gii_2010,
         gii_2019) %>%
  mutate(gii_diff = gii_2010 - gii_2019) %>%
  select(-gii_2019,-gii_2010)
head(gii_world)
tail(gii_world)
```
```{r}
library(countrycode)
country <- function(gii_world, iso3, destination = 'iso2c', nomatch = NA, warn = TRUE) {
    gii_cn <- gii_world[[iso3]]
    out <- countrycode(sourcevar = gii_cn,
                       origin = 'iso3c',
                       destination = destination)
    
    gii_world[[iso3]]<-out
    return(gii_world)
 }
gii_world <- country(gii_world, iso3 = "iso3") 
gii_world <- gii_world %>%
  rename(iso2='iso3') %>%
  filter(!is.na(iso2))
gii_world <- gii_world %>%
  select(-country)
head(gii_world)
```
```{r}
gii_merge <- World %>%
  merge(.,
        gii_world, 
        by.x="ISO", 
        by.y="iso2")%>%
  distinct()
print(gii_merge)
View(gii_merge)
```
```{r}
library(tmap)
library(tmaptools)
tmap_mode("plot")
qtm(gii_merge, 
    fill = "gii_diff")
```
```{r}
tmapgii <- gii_merge %>%
  st_bbox(.) %>% 
  tmaptools::read_osm(., type = "osm", zoom = NULL)
tmap_mode("plot")

tm_shape(tmapgii)+
tm_rgb()+
tm_shape(gii_merge) + 
tm_polygons("gii_diff", 
        style="jenks",
        palette="YlOrBr",
        midpoint=NA,
        alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Gender Inequality Index", legend.position = c("right", "bottom"))
```

```{r}
library(leafpop)
library(leaflet)

popupgii <- gii_merge %>%
  sf::st_drop_geometry()%>%
  dplyr::select(gii_diff, COUNTRY)%>%
  popupTable()

tmap::tmap_mode("view")

breaks = c(-0.1, -0.05, 0, 0.05, 0.1, 0.15, 0.5)

pal_gii<-gii_merge%>%
  colorBin(palette = "PuBu", domain=.$gii_diff,bins = breaks)

map <- leaflet(gii_merge) %>%
  addPolygons(color="white",
              weight = 2,
              opacity = 1,
              popup = popupgii,
              fillOpacity = 0.7,
              fillColor = ~pal_gii(gii_diff),
              group = "GII")%>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  addLegend(pal = pal_gii, values = ~gii_diff, position ="bottomleft", title = "Gender inequality index") %>%
  addLayersControl(
    baseGroups = c("OSM (default)", "CartoDB"),
    overlayGroups = c("Gii"),
    options = layersControlOptions(collapsed = FALSE)
  )
map
```

